import type { Metadata } from "next";
import { Poppins } from 'next/font/google'
import "./globals.css";
import { cn } from "@/lib/utils";
import BaseProvider from "@/components/providers/base-provider";

const poppins = Poppins({
  weight: ['100', '200', '300', '500', '600', '700', '800', '900'], subsets: ['latin'],
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html style={{
      colorScheme: "light",
    }}
      className="light"
      suppressHydrationWarning
      lang="en">
      <body
        className={cn(poppins?.className)}
      >
        <BaseProvider>
          {children}
        </BaseProvider>
      </body>
    </html>
  );
}
